const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"美术馆",
                        "menuJump":"列表",
                        "tableName":"meishuguan"
                    }
                ],
                "menu":"美术馆"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"美术馆收藏",
                        "menuJump":"列表",
                        "tableName":"meishuguanCollection"
                    }
                ],
                "menu":"美术馆收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"美术馆留言",
                        "menuJump":"列表",
                        "tableName":"meishuguanLiuyan"
                    }
                ],
                "menu":"美术馆留言"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-order",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"参观预约",
                        "menuJump":"列表",
                        "tableName":"meishuguanOrder"
                    }
                ],
                "menu":"参观预约"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-activity",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告通知",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告通知"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"展品信息",
                        "menuJump":"列表",
                        "tableName":"zhanpin"
                    }
                ],
                "menu":"展品信息"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"展品收藏",
                        "menuJump":"列表",
                        "tableName":"zhanpinCollection"
                    }
                ],
                "menu":"展品收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"展品留言",
                        "menuJump":"列表",
                        "tableName":"zhanpinLiuyan"
                    }
                ],
                "menu":"展品留言"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
